"""rename department

Revision ID: 965c6a54657b
Revises: ca7b3f32e4f4
Create Date: 2026-01-13 18:32:43.799445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965c6a54657b'
down_revision = 'ca7b3f32e4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
